### PR TITLE
Fix scan_pattern_page read bytes out of range.

### LINKED ISSUE #111: `pymem.pattern.scan_pattern_page` throw windows api error, code 299
**Describe the bug**
When scan with address which higher than mbi.BaseAddress, mbi.RegionSize will over read the memory.
Ref: https://github.com/srounet/Pymem/blob/4d8380c2e095461783f3f5f214843c40d2ea7684/pymem/pattern.py#L66C1-L66C1

**Your Environment**

1. Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
2. Win10 x64 19045.3570
3. Pymem 1.13.0

**Expected behavior**
Read correct size

**Traceback**
```python
start_address = pymem.pattern.pattern_scan_all(pid, aob)
# will throw error next line
end_address = pymem.pattern.scan_pattern_page(pid, start_address, end_aob)
```
---
Memory: 
|-------------------------- page ----------------------------------|
mbi.BaseAddress --- address

---
May `read_bytes` size be `mbi.RegionSize - (address - mbi.BaseAddress)`?

### PR DESCRIPTION
**Pull request by SakuraHentai**
fix #111

### CODE REVIEW

**Comment by jmctune** [comment]
With this patched in, I'm unfortunately still receiving WinApi 299 errors. from `read_bytes`.

**Comment by SakuraHentai** [comment]
> With this patched in, I'm unfortunately still receiving WinApi 299 errors from `read_bytes`.

Is your system is x64, and the target process is x86?

**Comment by jmctune** [comment]
> Is your system is x64, and the target process is x86?

Yes, that is correct. I'm using a 32-bit version of Python 3.11 as well.

**Comment by SakuraHentai** [comment]
> > Is your system is x64, and the target process is x86?
> 
> Yes, that is correct. I'm using a 32-bit version of Python 3.11 as well.

I just read your library code, it is scanning memory directly with `pattern_scan_all`, there starts with 0 that should be no offset problem, it is probably caused by other places.

But I've tried the 32-bit process on my computer and it doesn't reproduce it, sorry can't help you.

**Comment by jmctune** [comment]
Yep, it's nothing fancy. Just a class that's wrapping `pattern_scan_all`.

I have a few functions that will run a scan indefinitely. It could work for minutes or hours, but it will eventually throw a 299. No changes to the pattern, but the exception is in my linked mention above.

It's not `pattern_scan_all` itself, but `scan_pattern_page', which is called from above. As it's iterating over the pages, there's one page that trips it up while it's executing `read_bytes` over the pages.

**Comment by SakuraHentai** [comment]
> Yep, it's nothing fancy. Just a class that's wrapping `pattern_scan_all`.
> 
> I have a few functions that will run a scan indefinitely. It could work for minutes or hours, but it will eventually throw a 299. No changes to the pattern, but the exception is in my linked mention above.
> 
> It's not `pattern_scan_all` itself, but `scan_pattern_page`, which is called from above. As it's iterating over the pages, there's one page that trips it up while it's executing `read_bytes` over the pages.

Oh, I thought it reported an error on first run.

You can log the fields in the `mbi` when you get an error for debug, it's just the memory address where the mbi is located right now.

**Comment by srounet** [comment]
@StarrFox what's your thoughts on this ?

**Comment by StarrFox** [comment]
> @StarrFox what's your thoughts on this ?

seems fine to me

**Review by StarrFox — APPROVED** [review]

**Pull request merged**
